"""
api_server.py
-------------
FastAPI backend for the Semantic Bug Predictor & Auto-Fixer.

This module exposes two main endpoints:

  1. POST /predict
     - Input: Raw C/Java code (JSON)
     - Output: Bug detection result with confidence score

  2. POST /fix
     - Input: Buggy code (JSON)
     - Output: Corrected code generated by the fixer model

The server includes CORS middleware to allow requests from web frontends,
VS Code extensions, or any external client on different domains/ports.

Architecture:
  - Lazy-loads AI models on first request (to save startup time during dev)
  - Uses Pydantic models for request/response validation
  - Includes basic error handling and logging
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import logging

# Import the AI brain
from ai_models import AIModelManager

# ============================================================================
# Logging Setup
# ============================================================================
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ============================================================================
# Pydantic Models (Request/Response Schemas)
# ============================================================================


class CodeInput(BaseModel):
    """Request payload for code analysis."""

    code: str


class PredictResponse(BaseModel):
    """Response from /predict endpoint."""

    has_bug: bool
    confidence: float


class FixResponse(BaseModel):
    """Response from /fix endpoint."""

    original_code: str
    fixed_code: Optional[str]
    has_bug: bool


class AnalyzeFixResponse(BaseModel):
    """Response from /analyze_and_fix endpoint (detect + fix in one call)."""

    has_bug: bool
    confidence: float
    original_code: str
    fixed_code: Optional[str]


# ============================================================================
# FastAPI App Initialization
# ============================================================================

app = FastAPI(
    title="Semantic Bug Predictor & Auto-Fixer API",
    description="AI-powered backend for detecting and fixing semantic bugs in C/Java code",
    version="1.0.0",
)

# ============================================================================
# CORS Middleware
# ============================================================================
# This allows requests from web frontends (localhost:3000, localhost:8080, etc.)
# and other domains. For production, restrict allowed origins.

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production: ["https://yourdomain.com", ...]
    allow_credentials=True,
    allow_methods=["*"],  # Allow GET, POST, OPTIONS, etc.
    allow_headers=["*"],  # Allow all headers
)

# ============================================================================
# Global AI Model Manager (Lazy Loaded)
# ============================================================================
# We initialize the models only when the first request arrives.
# This saves startup time during development.

model_manager = None


def get_model_manager() -> AIModelManager:
    """Get or initialize the AI model manager (singleton pattern)."""
    global model_manager
    if model_manager is None:
        logger.info("Initializing AI models (first request)...")
        model_manager = AIModelManager()
    return model_manager


# ============================================================================
# API Endpoints
# ============================================================================


@app.get("/")
def read_root():
    """Health check and API info endpoint."""
    return {
        "message": "Semantic Bug Predictor & Auto-Fixer API is running",
        "endpoints": {
            "predict": "POST /predict - Detect bugs in code",
            "fix": "POST /fix - Generate fixed version of buggy code",
            "analyze_and_fix": "POST /analyze_and_fix - Detect and fix in one call",
        },
    }


@app.post("/predict", response_model=PredictResponse)
def predict_bug(payload: CodeInput):
    """Detect if code has a semantic bug.

    Endpoint: POST /predict

    Request:
        {
            "code": "int[] arr = new int[5];\nSystem.out.println(arr[10]);"
        }

    Response:
        {
            "has_bug": true,
            "confidence": 0.92
        }
    """
    if not payload.code or not payload.code.strip():
        raise HTTPException(
            status_code=400, detail="Code cannot be empty"
        )

    try:
        manager = get_model_manager()
        is_buggy, confidence = manager.detector.predict(payload.code)

        logger.info(
            f"Prediction: has_bug={is_buggy}, confidence={confidence:.4f}"
        )

        return PredictResponse(
            has_bug=is_buggy,
            confidence=round(confidence, 4),
        )
    except Exception as e:
        logger.error(f"Error during prediction: {str(e)}")
        raise HTTPException(
            status_code=500,
            detail=f"Prediction failed: {str(e)}",
        )


@app.post("/fix", response_model=FixResponse)
def fix_code(payload: CodeInput):
    """Generate a fixed version of buggy code.

    Endpoint: POST /fix

    Note: This endpoint does NOT check if code is actually buggy.
    It will attempt to fix whatever you give it. For a safer approach,
    use /analyze_and_fix which detects bugs first.

    Request:
        {
            "code": "int[] arr = new int[5];\nSystem.out.println(arr[10]);"
        }

    Response:
        {
            "original_code": "int[] arr = new int[5];\nSystem.out.println(arr[10]);",
            "fixed_code": "int[] arr = new int[5];\nif (10 < arr.length) System.out.println(arr[10]);",
            "has_bug": true
        }
    """
    if not payload.code or not payload.code.strip():
        raise HTTPException(
            status_code=400, detail="Code cannot be empty"
        )

    try:
        manager = get_model_manager()

        # First, detect if there's a bug
        is_buggy, _ = manager.detector.predict(payload.code)

        # Generate a fix
        fixed_code = manager.fixer.fix(payload.code) if is_buggy else None

        logger.info(
            f"Fix generated: has_bug={is_buggy}, "
            f"original_len={len(payload.code)}, "
            f"fixed_len={len(fixed_code) if fixed_code else 0}"
        )

        return FixResponse(
            original_code=payload.code,
            fixed_code=fixed_code,
            has_bug=is_buggy,
        )
    except Exception as e:
        logger.error(f"Error during fix generation: {str(e)}")
        raise HTTPException(
            status_code=500,
            detail=f"Fix generation failed: {str(e)}",
        )


@app.post("/analyze_and_fix", response_model=AnalyzeFixResponse)
def analyze_and_fix(payload: CodeInput):
    """Full pipeline: detect bug AND generate fix in one request.

    Endpoint: POST /analyze_and_fix

    This endpoint combines /predict and /fix for convenience.
    It detects if code has a bug, and if so, generates a fix.

    Request:
        {
            "code": "int[] arr = new int[5];\nSystem.out.println(arr[10]);"
        }

    Response:
        {
            "has_bug": true,
            "confidence": 0.92,
            "original_code": "int[] arr = new int[5];\nSystem.out.println(arr[10]);",
            "fixed_code": "..."
        }
    """
    if not payload.code or not payload.code.strip():
        raise HTTPException(
            status_code=400, detail="Code cannot be empty"
        )

    try:
        manager = get_model_manager()
        result = manager.analyze_and_fix(payload.code)

        logger.info(
            f"Analyze & Fix: has_bug={result['has_bug']}, "
            f"confidence={result['confidence']}"
        )

        return AnalyzeFixResponse(
            has_bug=result["has_bug"],
            confidence=result["confidence"],
            original_code=result["original_code"],
            fixed_code=result["fixed_code"],
        )
    except Exception as e:
        logger.error(f"Error during analyze_and_fix: {str(e)}")
        raise HTTPException(
            status_code=500,
            detail=f"Analysis failed: {str(e)}",
        )


# ============================================================================
# Startup Event (Optional)
# ============================================================================


@app.on_event("startup")
async def startup_event():
    """Called when the server starts (optional pre-warming)."""
    logger.info("FastAPI server starting up...")


@app.on_event("shutdown")
async def shutdown_event():
    """Called when the server shuts down (optional cleanup)."""
    logger.info("FastAPI server shutting down...")


if __name__ == "__main__":
    # Run with: uvicorn api_server:app --reload --host 0.0.0.0 --port 8000
    import uvicorn

    print("=" * 60)
    print("Starting Semantic Bug Predictor & Auto-Fixer API")
    print("=" * 60)
    print("Run with: uvicorn api_server:app --reload")
    print("Or: python api_server.py")
    print("=" * 60)

    uvicorn.run(app, host="0.0.0.0", port=8000)
